#+TITLE: Hello O!
#+AUTHOR: John, S
Test

* 금강경원문  

** 개경게(開經偈)
무상심심미묘법 無上甚深微妙法 위 없이 높고깊은 미묘한법
백천만겁난조우 百千萬劫難遭隅 백천만겁 지나도록 만나기 어려워라
아금문견득수지 我今聞見得修持 제가지금 보고듣고 수지하여
원해여래진실의 願解如來眞實義 여래의 참된뜻을 알고자 하나이다.

** 개법장진언(開法藏眞言)
옴 아라남 아라다(3번)
금강 마하 반야 바라밀경 (金剛摩訶般若波羅蜜經)

+ 1. 法會因由分 
如是我聞 一時. 佛 在舍衛國 祇樹給孤獨園 與大比丘衆千二百五十人俱
여시아문 일시  불 재사위국 기수급고독원 여대비구중천이백오십인구
爾時 世尊 食時 着衣持鉢 入舍 衛大城 乞食於其城中 次第乞已 還至本處
이시 세존 식시 착의지발 입사위대성  걸식어기성중 차제걸이 환지본처
飯食訖 收衣鉢 洗足已 敷座而坐 
반사흘 수의발 세족이 부좌이좌.

 2. 善現起請分 
時 長老 須菩提 在大衆中 卽從座起 偏袒右肩 右膝着地 合掌恭敬 而白佛言. 希有世尊.
시 장로 수보리 재대중중 즉종좌기 편단우견 우슬착지 합장공경 이백불언. 희유세존
如來 善護念諸菩薩 善付囑諸菩薩
여래 선호념제보살 선부촉제보살
世尊 善男子 善女人 發阿뇩 多羅三먁三菩提心 應云何住 云何降伏其心
세존 선남자 선여인 발아뇩다라삼먁삼보리심 응운하주 운하항복기심
佛言. 善哉善哉 須菩提 如汝所說 如來 善護念諸菩薩 善付囑諸菩薩 汝今諦請. 當爲汝說. 
불언. 선재선재. 수보리 여여소설 여래 선호념제보살 선부촉제보살. 여금제청. 당위여설.
善男子 善女人 發阿뇩多羅三먁三菩提心 應如是住 如是降伏其心 唯然 世尊 願樂欲聞
선남자 선여인 발아뇩다라삼먁삼보리심 응여시주 여시항복기심. 유연 세존 원요욕문

3. 大乘正宗分 
佛告. 須菩提 諸菩薩摩訶薩 應如是降伏其心. 
불고 수보리 제보살마아살 응여시항복기심.
所有一切衆生之類 若卵生 若胎生 若濕生 若化生 若有色 若無色 
소유일체중생지류 약란생 약태생 약습생 약화생 약유색 약무색
若有想 若無想 若非有想 非無想
약유상 약무상 약비유상 비무상 
我皆令入無餘涅槃 而滅度之 
아개영입무여열반 이멸도지
如是滅度無量無數無邊衆 生實無衆生得滅度者 
여시멸도무량무수무변중생 실무중생득멸도자
何以故 須菩提 若菩薩 有我相 人相 衆生相 壽者相 卽非菩薩 
하이고 수보리 약보살 유아상 인상 중생상 수자상 즉비보살

4. 妙行無住分 
復次 須菩提 菩薩 於法應無所住 行於布施
부차 수보리 보살 어법응무소주 행어보시
所謂不住色布施 不主聲香味觸法布施 
소위부주색보시 부주성향미촉법보시
須菩提 菩薩 應如是布施 不住於相
수보리 보살 응여시보시 부주어상
何以故 若菩薩 不住相布施 其福德 不可思量
하이고 약보살 부주상보시 기복덕 불가사량
須菩提 於意云何 東方虛空 可思量不. 不也世尊.
수보리 어의운하 동방허공 가사량부 불야세존
須菩提 南西北方 四維 上下 虛空 可思量 不. 不也世尊. 須菩提 菩薩 無住相布施福德
수보리 남서북방 사유 상하 허공 가사량 부. 불야세존. 수보리 보살 무주상보시복덕
亦復如是 不可思量
역부여시 불가사량
須菩提 菩薩 但應如所敎住 
수보리 보살 단응여소교주

5. 如理實見分 
須菩提 於意云何. 可以身相 見如來不.
수보리 어의운하 가이신상 견여래부.
不也 世尊. 不可以身相 得見如來
불야세존 불가이신상 득견여래
何以故 如來所說身相 卽非身相
하이고 여래소설신상 즉비신상
佛告. 須菩提 凡所有相 皆是虛妄 若見諸相 非相 卽見如來 
불고 수보리 범소유상 개시허망 약견제상 비상 즉견여래

6. 正信希有分 
須菩提 白佛言. 世尊 頗有衆生 得聞如是言說章句 生實信 不.
수보리 백불언 세존 파유중생 득문여시언설장구 생실신 부
佛告. 須菩提 莫作是說 如來 滅後 後五百歲 有持戒修福者 於此章句 能生信心 以此爲實
불고 수보리 막작시설. 여래 멸후 후오백세 유지계수복자 어차장구 능생신심 이차위실.
當知 是人 不於一佛二佛三四五佛 而種善根 已於無量千萬佛所 種諸善根 聞是章句 乃至
당지 시인 불어일불이불삼사오불 이종선근 이어무량천만불소 종제선근 문시장구 내지
一念生 淨信者
일념생 정신자.
須菩提 如來 悉知悉見. 是諸衆生 得如是無量福德.
수보리 여래 실지실견 시제중생 득여시무량복덕
何以故 是諸衆生 無復我相 人相 衆生相 壽者相. 無法相 亦無非法相
하이고 시제중생 무부아상 인상 중생상 수자상. 무법상 역무비법상
何以故 是諸衆生 若心取相 卽爲 着我人衆生壽者. 若取法相 卽着我人衆生壽者 何以故
하이고 시제중생 약심취상 즉위 착아인중생수자. 약취법상 즉착아인중생수자 하이고
若取非法相 卽着我人衆生壽者
약취비법상 즉착아인중생수자
是故 不應取法 不應取非法.
시고 불응취법 불응취비법
以是義故 如來常說 汝等比丘 知我說法 如筏喩者. 法尙應捨 何況非法.
이시의고 여래상설 여등비구 지아설법 여벌유자. 법상응사 하황비법

7. 無得無說分 
須菩提 於意云何. 如來 得阿뇩多羅三먁三菩提耶. 如來 有所說法耶 
수보리 어의운하 여래 득아뇩다라삼먁삼보리야 여래 유소설법야 
須菩提言. 如我解佛所說義 無有定法名阿뇩多羅三먁三菩提 亦無有定法如來可說.
수보리언 여야해불소설의 무유정법명아뇩다라삼먁삼보리 역무유정법여래가설
何以故 如來所說法 皆不可取 不可說 非法 非非法 
하이고 여래소설법 개불가취 불가설 비법 비비법
所以者何 一切賢聖 皆以無爲法 而有差別 
소이자하 일체현성 개이무위법 이유차별

8. 依法出生分 
須菩提 於意云何. 若人滿三千大千世界七寶 以用布施 是人所得福德 寧爲多 不.
수보리 어의운하 약인만삼천대천세계칠보 이용보시 즉시소득복덕 영위다 부
須菩提言 甚多 世尊. 何以故 是福德 卽非福德性 是故 如來說 福德多.
수보리언 심다 세존 하이고 시복덕 즉비복덕성 시고 여래설 복덕다
若復有人 於此經中受持 乃至 四句偈等 爲他人說 其福勝彼 
약부유인 어차경중수지 내지 사구게등 위타인설 기복승피
何以故 須菩提 一切諸佛 及 諸佛阿뇩多羅三약三菩提法 皆從此經出.
하이고 수보리 일체제불 급 제불아뇩다라삼먁삼보리법 개종차경출
須菩提 所謂佛法者 卽非佛法 
수보리 소위불법자 즉비불법.

9. 一相無相分 
須菩提 於意云何. 須陀洹 能作是念 我得須陀洹果 不. 
수보리 어의운하 수다원 능작시념 아득수다원과 부
須菩提言. 不也 世尊. 何以故 須陀洹 名爲入流 而無所入 不入色聲香味觸法 是名須陀洹
수보리언 불야 세존 하이고 수다원 명위입류 이무소입 불입색성 향미촉법 시명수다원
須菩提 於意云何. 斯陀含 能作是念 我得斯陀含果 不. 須菩提言. 不也 世尊. 何以故 斯陀含
수보리 어의운하 사다함 능작시념 아득사다함과 부. 수보리언 불야 세존 하이고 사다함
名一往來 而實無往來 是名斯陀含.
명일왕래 이실무왕래 시명사다함
須菩提 於意云何. 阿那含 能作是念 我得阿那含果 不. 須菩提言. 不也 世尊. 何以故 阿那含
수보리 어의운하 아나함 능작시념 아득아나함과 부 수보리언 불야 세존 하이고 아나함
名爲不來 而實無不來 是故 名阿那含.
명위불래 이실무불래 시고 명아나함
須菩提 於意云何. 阿羅漢 能作是念 我得阿羅漢道 不. 
수보리 어의운하 아라한 능작시념 아득아라한도 부.
須菩提言. 不也 世尊. 何以故 實無有法 名阿羅漢. 世尊 若阿羅漢作是念 我得阿羅漢道 
수보리언 불야 세존 하이고 실무유법 명아라한 세존 약아라한작시념 아득아라한도
卽爲着我人衆生壽者 
즉위착아인중생수자.
世尊 佛說我得無諍三昧人中 最爲 第一 是 第一離欲阿羅漢.
세존 불설아득무쟁삼매인중 최위 제일 시 제일이욕아라한.
世尊 我不作是念 我是離欲阿羅漢.
세존 아부작시념 아시이욕아라한.
世尊 我若作是念 我得阿羅漢道 世尊 卽不說 須菩提 是樂阿蘭那行者. 以須菩提實無所行
세존 아약작시념 아득아라한도 세존 즉불설 수보리 시요아란나행자. 이수보리실무소행
而名須菩提 是樂阿蘭那行 
이명수보리 시요아란나행

10. 莊嚴淨土分 
佛告 須菩提 於意云何. 如來昔在燃燈佛所 於法有所得 不. 不也 世尊. 如來在燃燈佛所 於法
불고 수보리 어의운하 여래석재연등불소 어법유소득 부 불야 세존 여래재연등불소 어법
實無所得.
실무소득
須菩提 於意云何. 菩薩莊嚴佛土 不.
수보리 어의운하 보살장엄불토 부
不也 世尊. 何以故 莊嚴佛土者 卽非莊嚴 是名莊嚴.
불야 세존 하이고 장엄불토자 즉비장엄 시명장엄
是故 須菩提 諸菩薩摩訶薩 應如 是生淸淨心. 不應住色生心 不應住聲香味觸法生心.
시고 수보리 제보살마아살 응여 시생청정심 불응주색생심 불응주성향미촉법생심
應無所住 而生其心. 
응무소주 이생기심
須菩提 譬如有人 身如須彌山王 於意云何. 是身爲大 不. 須菩提言. 甚大 世尊. 
수보리 비여유인 신여수미산왕 어의운하 시신위대 부 수보리언 심대 세존
何以故 佛說非身 是名大身 
하이고 불설비신 시명대신

11. 無爲福勝分 
須菩提 如恒河中所有沙數 如是沙等恒河 於意云何. 是諸恒河沙 寧爲多 不. 須菩提言 甚多
수보리 여항하중소유사수 여시사등항아 어의운하 시제항아사 영위다 부 수보리언 심다
世尊. 但諸恒河 尙多無數 何況其沙. 
세존 단제항아 상다무수 하항기사
須菩提 我今實言告汝. 若有善男子 善女人 以七寶滿爾所恒河沙數 三千大千世界 以用布施 
수보리 아금실연고여 약유선남자 선여인 이칠보만이소항하사수 삼천대천세계 이용보시
得福多 不. 須菩提言. 甚多 世尊.
득복다 부 수보리언 심다 세존
佛告. 須菩提 若善男子 善女人 於此經中 乃至 受持四句偈等 爲他人說 而此福德 勝前福德
불고 수보리 약선남자 선여인 어차경중 내지 수지사구계등 위타인설 이차복덕 승전복덕

12. 尊重正敎分 
復次 須菩提 隨說是經 乃至 四句偈等 當知此處 一切世間 天 人 阿修羅 皆應供養 如佛塔廟.
부차 수보리 수설시경 내지 사구계등 당지차처 일체세간 천 인 아수라 개응공양 여불탑묘.
何況有人 盡能受持讀誦 須菩提 當知是人 成就最上第一希有之法. 
하황유인 진능수지독송. 수보리 당지시인 성취최상제일희유지법.
若是經典所在之處 卽爲有佛 若尊重弟子 
약시경전소재지처 즉위유불 약존중제자

13.如法受持分

爾時 須菩提白佛言 世尊 當何名此經 我等云何奉持. 佛告. 須菩提是經 名爲金剛般若波羅蜜
이시 수보리백불언 세존 당하명차경 아등운하봉지 불고 수보리시경 명위금강반야바라밀
以是名字 汝當奉持
이시명자 여당봉지
所以者何 須菩提 佛說般若波羅蜜 卽非般若波羅蜜 是名般若波羅蜜 
소이자하 수보리 불설반야바라밀 즉비반야바라밀 시명반야바라밀
須菩提 於意云何 如來有所說法 不. 須菩提白佛言 世尊 如來無所說
수보리 어의운하 여래유소설법 부. 수보리백불언 세존 여래무소설
須菩提 於意云何 三千大千世界所有微塵 是爲多 不. 須菩提言 甚多. 世尊. 
수보리 어의운하 삼천대천세계소유미진 시위다 부 수보리언 심다 세존. 
須菩提 諸微塵如來說 非微塵 是名微塵 如來說世界 非世界 是名世界.
수보리 제미진여래설 비미진 시명미진 여래설세계 비세계 시명세계
須菩提 於意云何 可以三十二相見如來 不. 不也 世尊. 不可以三十二相得見如來 何以故
수보리 어의운하 가이삼십이상견여래 부. 불야 세존. 불가이삼십이상득견여래 하이고
如來說三十二相 卽是非相 是名三十二相
여래설삼십이상 즉시비상 시명삼십이상
須菩提 若有善男子 善女人 以恒河沙等身命布施 
수보리 약유선남자 선여인 이항아사등신명보시
若復有人 於此經中 乃至 受持四句偈等 爲他人說 其福甚多.
약유부인 어차경중 내지 수지사구계등 위타인설 기복심다.

14.離相寂滅分 

爾時 須菩提 聞說是經 深解義趣 涕淚悲泣 而白佛言. 希有 世尊. 佛說 如是甚深經典.
이시 수보리 문설시경 심해의취 체루비읍 이백불언 희유 세존 불설 여시심심경전
我從昔來 所得慧眼. 未曾得聞 如是之經.
아종석래 소득혜안 미증득문 여시지경
世尊 若復有人 得聞是經 信心淸淨 卽生實相 當知 是人成就第一 希有功德.
세존 약부유인 득문시경 신심청정 즉생실상 당지 시인성취제일 희유공덕
世尊 是實相者 卽是非相 是故 如來說名實相. 
세존 시실상자 즉시비상 시고 여래설명실상
世尊 我今得聞如是經典 信解受持 不足爲難
세존 아금득문여시경전 신해수지 부족위난
若當來世 後五百歲 其有衆生 得聞是經 信解受持 是人 卽爲第一希有. 
약당래세 후오백세 기유중생 득문시경 신해수지 시인 즉위제일희유
何以故 此人 無我相 無人相 無衆生相 無壽者相. 所以者何 我相 卽是非相 人相 衆生相 
하이고 차인 무아상 무인상 무중생상 무수자상 소이자하 아상 즉시비상 인상 중생상 
壽者相 卽是非相. 何以故 離一切諸相 卽名諸佛.
수자상 즉시비상 하이고 이일체제상 즉명제불
佛告. 須菩提 如是如是.
불고 수보리 여시여시
若復有人 得聞是經 不驚 不怖 不畏 當知 是人 甚爲希有.
약부유인 득문시경 불경 불포 불외 당지 시인 심위희유
何以故 須菩提 如來說第一波羅蜜 卽非第一波羅蜜 是名第一波羅蜜.
하이고 수보리 여래설제일바라밀 즉비제일바라밀 시명제일바라밀
須菩提 忍辱波羅蜜如來說 非忍辱波羅蜜.
수보리 인욕바라밀여래설 비인욕바라밀
何以故 須菩提 如我昔爲歌利王 割截身體 我於爾時 無我相 無人相 無衆生相 無壽者相.
하이고 수보리 여아석위가리왕 할절신체 아어이시 무아상 무인상 무중생상 무수자상
何以故 我於往昔節節支解時 若有 我相 人相 衆生相 壽者相 應生嗔恨.
하이고 아어왕석절절지해시 약유 아상 인상 중생상 수자상 응생진한.
須菩提 又念過去於五百世 作忍辱仙人 於爾所世 無我相 無人相 無衆生相 無壽者相 
수보리 우념과거어오백세 작인욕선인 어이소세 무아상 무인상 무중생상 무수자상
是故 須菩提 菩薩 應離一切相 發阿뇩多羅三먁三菩提心.
시고 수보리 보살 응리일체상 발아뇩다라삼먁삼보리심
不應住色生心 不應住聲香味觸法生心 應生無所住心.
불응주색생심 불응주성향미촉법생심 응생무소주심
若心有住 卽爲非住.
약심유주 즉위비주
是故 佛說 菩薩 心不應住色布施.
시고 불설 보살 심불응주색보시
須菩提 菩薩 爲利益一切衆生 應如是布施.
수보리 보살 위이익일체중생 응여시보시
如來說一切諸相 卽是非相 又說一切衆生 卽非衆生.
여래설일체제상 즉시비상 우설일체중생 즉비중생
須菩提 如來 是眞語者 實語者 如語者. 不狂語者 不異語者.
수보리 여래 시진어자 실어자 여어자. 불광어자 불이어자
須菩提 如來所得法 此法無實 無虛.
수보리 여래소득법 차법무실 무허.
須菩提 若菩薩 心住於法 而行布施如人入闇 卽無所見. 若菩薩 心不住法 而行布施 如人有目
수보리 약보살 심주어법 이행보시여인입암 즉무소견 약보살 심불주법 이행보시 여인유목
日光明照 見種種色.
일광명조 견종종색.
須菩提 當來之世 若有 善男子 善女人 能於此經 受持讀誦 卽爲如來 以佛智慧 悉知是人 
수보리 당래지세 약유 선남자 선여인 능어차경 수지독송 즉위여래 이불지혜 실지시인
悉見是人. 皆得成就 無量無邊功德.
실견시인 개득성취 무량무변공덕

15. 持經功德分 
須菩提 若有 善男子 善女人 初日分 以恒河沙等身布施 中日分 復以恒河沙等身布施 後日分
수보리 약유 선남자 선여인 초일분 이항하사등신보시 중일분 부이항아사등신보시 후일분
亦以恒河沙等身布施 如是無量百千萬億劫 以身布施
역이항하사등신보시 여시무량백천만억겁 이신보시 
若復有人 聞此經典 信心不逆 其福勝彼. 何況書寫受持讀誦 爲人解說.
약부유인 문차경전 신심불역 기복승피. 하황서사수지독송 위인해설
須菩提 以要言之 是經有 不可思議 不可稱量 無邊功德.
수보리 이요언지 시경유 불가사의 불가칭량 무변공덕
如來 爲發大乘者說 爲發最上乘者說 若有人 能受持讀誦 廣爲人說 如來 悉知是人 悉見是人.
여래 위발대승자설 위발최상승자설 약유인 능수지독송 광위인설 여래 실지시인 실견시인
皆得成就 不可量 不可稱 無有邊 不可思議功德. 如是人等 卽爲荷擔 如來阿뇩多羅三먁三菩提
개득성취 불가량 불가칭 무유변 불가사의공덕 여시인등 즉위하담 여래 아뇩다라삼먁삼보리
何以故 須菩提 若樂小法者 着我見 人見 衆生見 壽者見 卽於此經 不能聽受讀誦 爲人解說.
하이고 수보리 약요소법자 착아인 인견 중생견 수자견 즉어차경 불능청수독송 위인해설
須菩提 在在處處 若有此經 一切世間 天, 人, 阿修羅 所應供養. 當知 此處 卽爲是塔 皆應恭敬
수보리 제제처처 약유차경 일체세간 천, 인, 아수라 소응공양. 당지 차처 즉위시탑 개응공경 
作禮圍繞 以諸華香 而散其處
작례위요 이제화향 이산기처

16. 能淨業障分 
復次 須菩提 善男子 善女人 受持讀誦此經 若爲人輕賤 是人 先世罪業 應墮惡道 以今世人輕賤
부차 수보리 선남자 선여인 수지독송차경 약위인경천 시인 선세죄업 응타악도 이금세인경천
故 先世罪業 卽爲消滅 當得阿뇩多羅三먁三菩提. 
고 선세죄업 즉위소멸 당득아뇩다라삼먁삼보리
須菩提 我念過去無量阿僧祗劫 於燃燈佛前 得値八百四千萬億那由他 諸佛 悉皆供養承事 
수보리 아념과거무량아승지겁 어연등불전 득치팔백사천만억나유타 제불 실개공양승사
無空過者.
무공과자
若復有人 於後末世 能受持讀誦此經 所得功德 於我所供養諸佛功德 百分 不及一 千萬億分乃
약부유인 어후말세 능수지독송차경 소득공덕 어아소공양제불공덕 백분 불급일 천만억분내
至算數譬喩 所不能及.
지산수비유 소불능급.
須菩提 若善男子 善女人 於後末世 有受持讀誦此經 所得功德 我若 具說者 或有人聞 心卽狂
수보리 약선남자 선여인 어후말세 유수지독송차경 소득공덕 아약 구설자 혹유인문 심즉광
亂 狐疑不信. 
란 호의불신.
須菩提 當知 是經義 不可思議 果報 亦不可思議 
수보리 당지 시경의 불가사의 과보 역불가사의.

17. 究竟無我分 
爾時 須菩提白佛言 世尊 善男子 善女人 發阿뇩多羅三먁三菩提心 云何應住 云何降伏其心.
이시 수보리백불언 세존 선남자 선여인 발아뇩다라삼먁삼보리심 운하응주 운하항복기심
佛告. 須菩提 若善男子 善女人 發阿뇩多羅三먁三菩提心者 當生如是心 我應滅度一切衆生 
불고 수보리 약선남자 선여인 발아뇩다라삼먁삼보리심자 당생여시심 아응멸도일체중생 
滅度一切衆生已 而無有一衆生 實滅度者. 
멸도일체중생이 이무유일중생 실멸도자
何以故 須菩提 若菩薩 有我相 人相 衆生相 壽者相 卽非菩薩 
하이고 수보리 약보살 유아상 인상 중생상 수자상 즉비보살
所以者何 須菩提 實無有法 發阿뇩多羅三먁三菩提心者.
소이자하 수보리 실무유법 발아뇩다라삼먁삼보리심자
須菩提 於意云何 如來 於燃燈佛 所有法得阿뇩多羅三먁三菩提 不.
수보리 어의운하 여래 어연등불 소유법득아뇩다라삼먁삼보리 부
不也 世尊. 如我解佛所說義 佛於 燃燈佛所 無有法得阿뇩多羅三먁三菩提.
불야 세존 여아해불소설의 불어 연등불소 무유법득아뇩다라삼먁삼보리
佛言. 如是如是.
불언 여시여시
須菩提 實無有法如來得阿뇩多羅三먁三菩提 須菩提 若有法如來得阿뇩多羅三먁三菩提者 
수보리 실무유법여래득아뇩다라삼먁삼보리 수보리 약유법여래득아뇩다라삼먁삼보리자
燃燈佛 卽不與我授記 汝於來世 當得作佛 號釋迦牟尼. 以實無有法得阿뇩多羅三먁三菩提 
연등불 즉불여아수기 여어래세 당득작불 호석가모니. 이실무유법득아뇩다라삼먁삼보리
是故 燃燈佛 與我授記 作是言 汝於來世 當得作佛 號釋迦牟尼.
시고 연등불 여아수기 작시언 여어래세 당득작불 호석가모니
何以故 如來者 卽諸法如義.
하이고 여래자 즉제법여의
若有人言 如來得阿뇩多羅三먁三菩提 須菩提 實無有法佛得阿뇩多羅三먁三菩提.
약유인언 여래득아뇩다라삼먁삼보리 수보리 실무유법불득아뇩다라삼먁삼보리
須菩提 如來所得阿뇩多羅三먁三菩提 於是中 無實 無虛.
수보리 여래소득아뇩다라삼먁삼보리 어시중 무실 무허
是故 如來說一切法 皆是佛法.
시고 여래설 일체법 개시불법
須菩提 所言一切法者 卽非一切法 是故 名一切法.
수보리 소언일체법자 즉비일체법 시고 명일체법
須菩提 譬如人身長大. 須菩提言. 世尊 如來說人身長大 卽爲非大身 是名大身.
수보리 비여인신장대 수보리언 세존 여래설인신장대 즉위비대신 시명대신
須菩提 菩薩 亦如是. 若作是言 我當滅度 無量衆生 卽不名菩薩.
수보리 보살 역여시 약작시언 아당멸도 무량중생 즉불명보살
何以故 須菩提 實無有法 名爲菩薩 是故 佛說一切法 無我 無人 無衆生 無壽者.
하이고 수보리 실무유법 명위보살 시고 불설일체법 무아 무인 무중생 무수자
須菩提 若菩薩 作是言 我當莊嚴佛土 是不名菩薩.
수보리 약보살 작시언 아당장엄불토 시불명보살
何以故 如來說莊嚴佛土者 卽非莊嚴 是名莊嚴.
하이고 여래설장엄불토자 즉비장엄 시명장엄
須菩提 若菩薩 通達無我法者 如來說 名眞是菩薩. 
수보리 약보살 통달무아법자 여래설 명진시보살

18. 一切同觀分 
須菩提 於意云何 如來有肉眼 不. 如是 世尊. 如來有肉眼.
수보리 어의운하 여래유육안 부 여시 세존 여래유육안
須菩提 於意云何 如來有天眼 不. 如是 世尊. 如來有天眼.
수보리 어의운하 여래유천안 부. 여시 세존 여래유천안
須菩提 於意云何 如來有慧眼 不. 如是 世尊. 如來有慧眼
수보리 어의운하 여래유혜안 부. 여시 세존 여래유혜안
須菩提 於意云何 如來有法眼 不. 如是 世尊. 如來有法眼.
수보리 어의운하 여래유법안 부 여시 세존 여래유법안
須菩提 於意云何 如來有佛眼 不. 如是 世尊 如來有佛眼.
수보리 어의운하 여래유불안 부. 여시 세존 여래유불안
須菩提 於意云何 如恒河中所有沙佛說是沙 不. 如是 世尊. 如來說是沙.
수보리 어의운하 여항하중소유사불설시사 부. 여시 세존 여래설시사
須菩提 於意云何 如一恒河中所有沙 有如是沙等恒河.
수보리 어의운하 여일항하중소유사 유여시사등항하
是諸恒河所有沙數佛世界 如是寧爲多 不. 甚多世尊.
시제항아소유사수불세계 여시영위다 부. 심다세존.
佛告. 須菩提 爾所國土中所有衆生
불고 수보리 이소국토중소유중생
若干種心 如來悉知.
약간종심 여래실지
何以故 如來說諸心 皆爲非心 是名爲心.
하이고 여래설제심 개위비심 시명위심
所以者何 須菩提 過去心不可得 現在心不可得 未來心不可得 .
소이자하 수보리 과거심불가득 현재심불가득 미래심불가득

19. 法界通化分 
須菩提 於意云何 若有人 滿三千大千世界七寶 以用布施 是人 以是因緣 得福多 不. 如是 世尊
수보리 어의운하 약유인 만삼천대천세계칠보 이용보시 시인 이시인연 득복다 부. 여시 세존
此人 以是因緣 得福 甚多. 
차인 이시인연 득복 심다
須菩提 若福德有實 如來不說 得福德多. 以福德無故 如來說 得福德多 
수보리 약복덕유실 여래불설 득복덕다. 이복덕무고 여래설 득복덕다

20. 離色離相分 
須菩提 於意云何. 佛 可以具足色身見 不. 不也 世尊. 如來 不應以具足色身見 何以故 如來說
수보리 어의운하 불 가이구족색신견 부 불야 세존 여래 불응이구족색신견 하이고 여래설
具足色身 卽非具足色身 是名具足色身. 
구족색신 즉비구족색신 시명구족색신.
須菩提 於意云何 如來 可以具足諸相見 不. 不也 世尊. 如來 不應以具足諸相見. 何以故 如來
수보리 어의운하 여래 가이구족제상견 부. 불야 세존 여래 불응이구족제상견 하이고 여래
說諸相 具足 卽非具足 是名諸相具足. 
설제상 구족 즉비구족 시명제상구족

21. 非說所說分 
須菩提 汝 勿謂 如來作是念 我當 有所說法 莫作是念.
수보리 여 물위 여래작시념 아당 유소설법 막작시념
何以故 若人言 如來有所說法 卽爲謗佛 不能解我所說故.
하이고 약인언 여래유소설법 즉위방불 불능해아소설고
須菩提 說法者 無法可說 是名說法.
수보리 설법자 무법가설 시명설법
爾時 慧命須菩提白佛言 世尊 頗有衆生 於未來世 聞說是法 生信心不. 佛言. 須菩提 彼非衆生
이시 혜명수보리백불언 세존 파유중생 어미래세 문설시법 생신심부 불언 수보리 피비중생
非不衆生. 何以故 須菩提 衆生衆生者如來說 非衆生 是名衆生 
비불중생 하이고 수보리 중생중생자여래설 비중생 시명중생

22. 無法可得分 
須菩提白佛言. 世尊 佛得阿뇩多羅三먁三菩提 爲無所得耶. 佛言. 如是如是 須菩提 我於阿뇩多
수보리백불언 세존 불득아뇩다라삼먁삼보리 위무소득야 불언 여시여시 수보리 아어아뇩다
羅三먁三菩提 乃至 無有少法可得 是名 阿뇩多羅三먁三菩提.
라삼먁삼보리 내지 무유소법가득 시명 아뇩다라삼먁삼보리

23. 淨心行善分 
復次 須菩提 是法平等無有高下 是名阿뇩多羅三먁三菩提. 
부차 수보리 시법평등무유고하 시명아뇩다라삼먁삼보리
以無我 無人 無衆生 無壽者 修一切善法 卽得阿뇩多羅三먁三菩提.
이무아 무인 무중생 무수자 수일체선법 즉득아뇩다라사먁삼보리
須菩提 所言善法者如來說 卽非善法 是名善法 
수보리 소언선법자여래설 즉비선법 시명선법

24. 福智無比分 
須菩提 若三千大千世界中所有諸 須彌山王 如是等七寶聚 有人 持用布施 若人 以此般若波羅蜜
수보리 약삼천대천세계중소유제 수미산왕 여시등칠보취 유인 지용보시 약인 이차반야바라밀
經 乃至 四句偈等 受持讀誦 爲他人說 於前福德 百分 不及一 百千萬億分 乃至 算數譬喩 所不
경 내지 사구계등 수지독송 위타인설 어전복덕 백분 불급일 백천만억분 내지 산수비유 소불
能及.
능급

25. 化無所化分 
須菩提 於意云何 汝等 勿謂 如來作是念 我當度衆生 須菩提 莫作是念 
수보리 어의운하 여등 물위 여래작시념 아당도중생 수보리 막작시념
何以故 實無有衆生如來度者.
하이고 실무유중생여래도자
若有衆生如來度者 如來 卽有我人衆生壽者. 
약유중생여래도자 여래 즉유아인중생수자 
須菩提 如來說有我者 卽非有我 而凡夫之人 以爲有我. 須菩提 凡夫者如來說 卽非凡夫 
수보리 여래설유아자 즉비유아 이범부지인 이위유아 수보리 범부자여래설 즉비범부 
是名凡夫
시명범부

26. 法身 非相分
須菩提 於意云何. 可以三十二相 觀如來 不.
수보리 어의운하. 가이삼십이상 관여래 부.
須菩提言. 如是如是. 以三十二相 觀如來.
수보리언. 여시여시. 이삼십이상 관여래.
佛言. 須菩提 若以三十二相 觀如來者 轉輪聖王 卽是如來.
불언. 수보리 약이삼십이상 관여래자 전륜성왕 즉시여래.
須菩提白佛言. 世尊 如我解佛所設義 不應以三十二相 觀如來.
수보리백불언. 세존 여아해불소설의 불응이삼십이상 관여래.
爾時 世尊 而說偈言
이시 세존 이설게언
若以色見我 以音聲求我 是人行邪道 不能見如來 
약이색견아 이음성구아 시인행사도 불능견여래

27. 無斷無滅分 
須菩提 汝若作是念 如來不以具足相 故得阿뇩多羅三먁三菩提. 須菩提 莫作是念 如來 不以具
수보리 여약작시념 여래불이구족상 고득아뇩다라삼먁삼보리. 수보리 막작시념 여래 불이구
足相 故得阿뇩多羅三먁三菩提.
족상 고득아뇩다라삼먁삼보리.
須菩提 汝若作是念 發阿뇩多羅三먁三菩提心者 說諸法斷滅 莫作是念 
수보리 여약작시념 발아뇩다라삼먁삼보리심자 설제법단멸 막작시념
何以故 發阿뇩多羅三먁三菩提心者 於法不說斷滅相 
하이고 발아뇩다라삼먁삼보리심자 어법불설단멸상

28. 不受不貪分 
須菩提 若菩薩 以滿恒河沙等世界七寶 持用布施 若復有人 知一切法無我 得成於忍 此菩薩 
수보리 약보살 이만항하사등세계칠보 지용보시 약부유인 지일체법무아 득성어인 차보살
勝前菩薩所得功德.
승전보살소득공덕
何以故 須菩提 以諸菩薩 不受福德故 
하이고 수보리 이제보살 불수복덕고
須菩提白佛言. 世尊 云何菩薩 不受福德. 須菩提 菩薩 所作福德 不應貪着 是故說 不受福德.
수보리백불언 세존 운하보살 불수복덕 수보리 보살 소작복덕 불응탐착 시고설 불수복덕.

29. 威儀寂靜分 
須菩提 若有人言 如來 若來 若去 若坐 若臥 是人 不解我所說義.
수보리 약유인언 여래 약래 약거 약좌 약와 시인 불해아소설의.
何以故 如來者 無所從來 亦無所去 故名如來. 
하이고 여래자 무소종래 역무소법 고명여래

30. 一合理相分 
須菩提 若善男子 善女人 以三千大千世界 碎爲微塵. 於意云何. 是微塵衆 寧爲多 不. 須菩提言
수보리 약선남자 선여인 이삼천대천세계 쇄위미진 어의운하 시미진중 영위다 부. 수보리언
甚多 世尊. 何以故 若是微塵衆 實有者 佛卽不說 是微塵衆. 所以者何 佛說微塵衆 卽非微塵衆
심다 세존 하이고 약시미진중 실유자 불즉불설 시미진중 소이자하 불설미진중 즉비미진중
是名微塵衆.
시명미진중
世尊 如來所說三千大千世界 卽非世界 是名世界.
세존 여래소설삼천대천세계 즉비세계 시명세계.
何以故 若世界 實有者 卽是一合相. 如來說 一合相 卽非一合相 是名一合相
하이고 약세계 실유자 즉시일합상 여래설 일합상 즉비일합상 시명일합상
須菩提 一合相者 卽是不可說 但凡夫之人 貪着其事. 
수보리 일합상자 즉시불가설 단범부지인 탐착기사

31. 知見不生分 
須菩提 若人言 佛說 我見 人見 衆生見 壽者見. 須菩提 於意云何. 是人解我所說義 不. 不也
수보리 약인언 불설 아견 인견 중생견 수자견 수보리 어의운하 시인해아소설의 부 불야
世尊. 是人 不解如來所說義.
세존 시인 불해여래소설의
何以故 世尊說 我見 人見 衆生見 壽者見 卽非我見 人見 衆生見 壽者見 是名 我見 人見 
하이고 세존설 아견 인견 중생견 수자견 즉비아견 인견 중생견 수자견 시명 아견 인견
衆生見 壽者見.
중생견 수자견
須菩提 發阿뇩多羅三먁三菩提心者 於一切法 應如是知 如是見 如是信解. 不生法相.
수보리 발아뇩다라삼먁삼보리심자 어일체법 응여시지 여시견 여시신해 불생법상
須菩提 所言法相者如來說 卽非法相 是名法相. 
수보리 소언법상자여래설 즉비법상 시명법상.

32. 應化非眞分 
須菩提 若有人 以滿無量阿僧祗世界七寶 持用布施 若有善男子 善女人 發菩薩心者 持於此經
수보리 약유인 이만무량아승지세계칠보 지용보시 약유선남자 선여인 발보살심자 지어차경
乃至 四句偈等 受持讀誦 爲人演說 其福勝彼.
내지 사구게등 수지독송 위인연설 기복승피
云何爲人演說.
운하위인연설
不取於相 如如 不動
불취어상 여여 부동
何以故 一切有爲法 如夢幻泡影 如露亦如電 應作如是觀
하이고 일체유위법 여몽환포영 여로역여전 응작여시관
佛說是經已 長老 須菩提 及諸比丘 比丘尼 優婆塞 優婆尼 一切世間 天 人 阿修羅 聞佛所說
불설시경이 장로 수보리 급제비구 비구니 우바새 우바이 일체세간 천 인 아수라 문불소설
皆大歡喜 信受奉行.
개대환희 신수봉행.
마하 반야 바라밀.
