차를 마실 때, 마시기 시작부터 매우 세심한 주의가 필요하다.
차를 다린다는 것은 온도와 시간과의 투쟁이다. 


숙우(熟盂) - 차호 - 숙우 - 찻잔, 숙우는 일종의 제조상의 모나드.
정화수, 정안수


* 차를 마시기 전


* 방법 

** 찻잎에 물이 닿기 전까지
*** 물을 끓인다 - 물은 100도까지 끓인다.
*** 끓인 물을 물 항아리에 넣고 차호,숙우,  찻잔 모두 씻어낸다.
**** 차호-> 숙우 -> 찻잔 의 순서
**** 씻어내는 것과 동시에 온도를 높인다. 1분정도 시간을 가지고 천천히.

** 찻잎에 물이 닿은 후부터
*** 찻잎을 차호에 넣고 적당한 온도의 물을 넣는다.
**** 첫번째 물은 찻잎을 씻어낸다. 많이 부을 것  없이 반만 넣고, 신속하게 헹구어 낸다.
**** 두번째 물부터 가득 넣고, 적당한 시간으로 다린다.
*** 차호를 들고 차해에 바닥을 한번 닦아 낸 후 숙우에 차를 따른다.
*** 숙우의 차를 찻잔에 따른다.


* 의미

** 인간
   찻잔에 차를 따랐다면, 모두 각자의 앞에는 찻잔이 있고, 그 안에는 차가 들어있다. 차에는 찻잎 성분이 있으며, 찻잎은 자연을 상징하고, 자연의 성분을 내포하고, 자연의 시간을 함축하고 있다. 이렇게 정제되고 압축된  자연 즉 찻잎의 성분이 물에 녹아 있다. 보통의 차가 없는 상황에서의 매 개인의 에고에 있어서 방어막 같은 막이 있다면, 그 방어막은 각자에 따라서 다르며, 다르기 때문에 부딪힐 수 있는 것이다. 어떻게 하면 이러한 부딪힘을 막을 수 있을까? 그 해답은 각자의 앞에 있는 조그만 찻잔에 있을 수 있는 것인가?

** 주술적 가능성
   예전에 정성으로 기도를 할 때를 보면 정화수라는 수단이 나오는데,  정화수는 정안수로도 불리며 이른 새벽에 길은 우물물을 말한다.  우물은 자연의 틈이다. 자연의 틈에서 자연의 것이 나오는데 이는 물이며, 자연 속에서 나온 것이기 때문에 자연속으로 들어갈 수 있는 가능성을 내포하고 있음에 그 물을 길어 자연에 뿌리 박고 있는 나무나 돌 앞에서 그 물을 놓고 그 것보다 자연과 떨어져 있는 부평초 같은 사람이 그 마음 속의 형체 없는 무엇을 비는 것이다. 빈다는 것은 그 물과 나무의 보다 자연에 가까운 힘을 빌린다는 것이며, 빌어서 비는 것이다. 
   이제 각자의 앞에 있는 찻잔을 본다면, 그 때의 찻잔 속의 차는 단순한 수분을 포함한 음료가 아니며, 단지 몸을 적시기 위한 물리적 성분이 아닌, 각 개인의 마음을 적실 수 있는, 마음을 적시어 그 마음 속의 형체없는 것들이 무의식적으로 소통할 수 있게 하는 하나의 수단일 수 있는 것이다. 말을 시작하지 않았어도 이미 통하고 있음을 의미한다.

   
** 술은 차와 같은 가능성이 없는가?
    술은 발효과정을 거친 음료이며, 발효라는 것은 본래의 성분이 어느정도 변질된 혹은 그 과정중에 생성된 것을 즐길 수 있는 음료이다. 술을 마시면 취하는데, 발효과정 중에 변화는 과정에서의 고통의 산물을 마시기 때문일 것이다. 인생을 추상화하면 생로병사로 할 수 있는데, 병의 과정을 극히 늘렸으니 그 고통은 말하기 힘든 것이며,  자연속 무언가의 고통을 흡수한다는 것은 그 괴로움을 제정신으로 흡수할 수 없기에 취하는 것이다.  이렇게 취한다면, 같이 취한다면 취한 상태의 소통은 가능할 것이다. 그러나 이러한 소통은 깊은 산속의  맑은 아침 이슬을 머금었던 찻잎의 숨결과는 같을 수 없다. 술은 속세의 홍진과 같은 자연의 눈물이다. 눈물을 마시고 있다면 평상심을 유지할 수 없을 것이다. 
   

    



   
   
   
    
   
 
