
* Start
  I was walking to class today. and I noticed this...

  little 🌿sprig of green, pushing its way out of the cement.

  Now, I couldn't tell if it was a flower, a plant, or a weed.

  .. But I respected its persistence. ... ...

  We all have a ceiling .. like that 🌿sprig. And like that little 🌿sprig did, ...

  We have to break through .. to achieve our full potential.

  For my new students, .. this is your first step.

  Today is your first step in your growth .. toward what you're meant to be.


  Now, I only noticed that, ... 'cause that woman in front of me, ..

  She stepped aside so not to step on it. ...

  Let's come to standing, please, Warm up.


  /Big inhale/

  /Rise/

  /Exhale and swan dive into your forward fold. Keep your knees bent, ~ease your body into that stretch./

  *Beautiful*  ..

  *Bravo* ...

  Now, that woman was exactly what you imagined, lot in hand on her cell phone.

  /Big inhale, hands to knees, halfway left/

  *Beautiful, long spine* ...

  What's the lesson here? ..

  Hmm? ...

  That 🌿sprig was small .. It was insignificant, it was .. in an inconvenient place. it probably had no right to be in! ...

  But it wasn't ashamed.

  /Exhale, drawing back into your forward fold/

  It could have been just a weed, but ... she steped aside.

  The world wants you to be exactly like that.

  Small

  Insignificant

  Inconvenient

  /Rise with a flat back/

  /Big inhale, exhale, hands to heart/  🙏

  *Beautiful* 

  But if you stand tall, ... if you are who you are with no apology ...

  the world has to reckon with you.

  It will have to.

  Let us begin.

  Om 🎵


* Asana

  This is warrior two. ...

  This one hurts. .. I know ... But It was supposed to hurt ... ...

  Legs are shaking .. Arms are aching .. I know

  But the key to this pose is standing tall.

  Grow through your heart. ...

  I know, it's supposed to burn. ... 

  Welcome the pain. ..

  Embrace the discomfort.

  👂'You are ascending'

  But that's the thing about we warriors.


  We stand tall when it hurts .. especially when it hurts .. when it aches.

  We stand tall, like that little 🌿sprig.  🤸

  /Breathe/

  
