name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v1

      - name: Install emacs
        run: sudo apt install emacs-nox --yes


      - name: Build the site
        run: ./build.sh

      - name: Publish GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
	with:
	  branch: gh-pages
	  folder: public

